ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings, urls

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('ProyectoWebApp.urls')),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('administrador/', include('administrador.urls')),

    
]

administrador/urls.py
from django.urls import path
from . import views

app_name = 'administrador'

urlpatterns = [

    path('usuarios/', views.user, name='usuarios'),
    path('editarUser/<int:user_id>/', views.edit_user, name='usuariosEdit'),
    path('eliminarUser/<int:user_id>/', views.delete_user, name='usuariosDelet'),
    path('agregarUser/', views.add_user, name='usuariosAdd'),

    path('roles/', views.rol, name='roles'),
    path('rolesUsuario/<int:user_id>/', views.rolUser, name='rolesUsuario'),
    path('eliminarRolesUsuario/<int:user_id>/<int:permission_id>/', views.delete_rolUser, name='rolesUsuarioDelet'),
    path('agregarRolesUsuario/<int:user_id>/', views.add_rolUser, name='rolesUsuarioAdd'),
    path('agregarRol/<int:user_id>/<int:permission_id>', views.agregarRol, name='agregarPermiso'),
    

    path('blogs/', views.blog, name='blogs'),
    path('editBlog/<int:post_id>/', views.edit_blog, name='blogEdit'),
    path('deleteBlog/<int:post_id>/', views.delete_blog, name='blogDelete'),
    path('addBlog/', views.add_blog, name='blogAdd'),

    path('blogsCategorias/', views.blogsCategorias, name='blogsCategorias'),
    path('addBlogCategoria/', views.add_blogCategoria, name='blogCategoriaAdd'),
    path('editBlogCategoria/<int:postCategoria_id>/', views.edit_blogCategoria, name='blogCategoriaEdit'),

    path('servicios/', views.servicios, name='servicios'),
    path('editServicio/<int:servicio_id>/', views.edit_servicios, name='servicioEdit'),
    path('deleteServicio/<int:servicio_id>/', views.delete_servicios, name='servicioDelete'),
    path('addServicio/', views.add_servicios, name='servicioAdd'),

    path('productos/', views.productos, name='productos'),
    path('editProducto/<int:producto_id>/', views.edit_productos, name='productoEdit'),
    path('deleteProducto/<int:producto_id>/', views.delete_productos, name='productoDelete'),
    path('addProducto/', views.add_productos, name='productoAdd'),

    path('productosCategorias/', views.categotiasProd, name='productosCategorias'),
    path('addProductosCategoria/', views.add_categoriasProd, name='productosCategoriaAdd'),
    path('editProductosCategoria/<int:categoriaProd_id>/', views.edit_categoriasProd, name='productosCategoriaEdit'),

    path('grupos/', views.grupos, name='grupos'),
    path('unGrupo/<int:grupo_id>/', views.unGrupo, name='traerObjetosDeGrupo'),
    path('agregarUsuario/<int:grupo_id>/', views.addUsuarioGrupo, name='agregarUsuario'),
    path('agregarPermiso/<int:grupo_id>/', views.addPermisoGrupo, name='agregarPermiso'),
    path('eliminarUsuario/<int:grupo_id>/<int:user_id>/', views.deleteUsuarioGrupo, name='eliminarUsuario'),
    path('eliminarPermiso/<int:grupo_id>/<int:permiso_id>/', views.deletePermisoGrupo, name='eliminarPermiso'),
    
    
      
]

blog/urls.py
from django.urls import path
from blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', views.post, name="Blog"),
    path('categoria/<categoria_id>/', views.categoria, name="categoria")
 
]

administrador/models.py
from django.db import models

# Create your models here.

administrador/forms.py
from django import forms
from blog.models import Post, Categoria
from pedidos.models import User
from servicios.models import Servicio
from tienda.models import Producto, CategoriaProd


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email'] 
        
class UserAddForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'email']    


class BlogEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['titulo', 'contenido', 'imagen', 'categorias', 'autor']

class BlogAddForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['titulo', 'contenido', 'imagen', 'categorias', 'autor']


class BlogCategoriaAddForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre']

class BlogCategoriaEditForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre']


class ServicioAddForm(forms.ModelForm):
   class Meta:
        model = Servicio
        fields = ['titulo', 'contenido', 'imagen']

class ServicioEditForm(forms.ModelForm):
    class Meta:
            model = Servicio
            fields = ['titulo', 'contenido', 'imagen']


class ProductoAddForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'categoria', 'imagen', 'precio', 'disponibilidad']

class ProductoEditForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'categoria', 'imagen', 'precio', 'disponibilidad']


class ProductoCategoriaAddForm(forms.ModelForm):
    class Meta:
        model = CategoriaProd
        fields = ['nombre']

class ProductoCategoriaEditForm(forms.ModelForm):
    class Meta:
        model = CategoriaProd
        fields = ['nombre']

administrador/views.py
import datetime
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User, Group
from blog.models import Post, Categoria
from servicios.models import Servicio
from .forms import *
from datetime import datetime
from .permissions import *
from django.contrib.auth.models import Permission


#Trabajando con usuarios
@view_user_permission
def user(request):
    users = User.objects.all()
    return render(request, "usuarios/usuarios.html", {"users": users})

@edit_user_permission
def edit_user(request, user_id):

    user = get_object_or_404(User, id=user_id)
    
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=user)  # Si tienes un formulario de edición, pásale los datos y la instancia del usuario
        if form.is_valid():
            form.save()
            return redirect('administrador:usuarios')  # Redirige a la vista de lista de usuarios o a donde quieras
    else:
        form = UserEditForm(instance=user)  # Si es una solicitud GET, crea una instancia del formulario con los datos actuales del usuario
    
    return render(request, 'usuarios/editar_usuario.html', {'form': form, 'user': user})

@delete_user_permission
def delete_user(request, user_id):

    user = get_object_or_404(User, id=user_id)
    
    if request.method == 'POST':
        user.delete()
        return redirect('administrador:usuarios')  # Redirige a la vista de lista de usuarios o a donde quieras
    
    return render(request, 'usuarios/eliminar_usuario.html', {'user': user})

@add_user_permission
def add_user(request):
    if request.method == 'POST':
        form = UserAddForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.last_login = datetime.now()  # Asigna la fecha y hora actual en la zona horaria local
            user.save()
            return redirect('administrador:usuarios')
    else:
        form = UserAddForm()

    template = 'usuarios/agregar_usuario.html'
    return render(request, template, {'form': form})



#Trabajando con roles
@view_rol_permission
def rol(request):

    # Obtener una lista de usuarios con sus permisos
    users_with_permissions = User.objects.prefetch_related('user_permissions').all()

    context = {
        'users_with_permissions': users_with_permissions
    }

    return render(request, 'roles/usuarios_roles.html', context)

def rolUser(request, user_id):
    user = get_object_or_404(User, id=user_id)  # Obtener el usuario o mostrar 404 si no existe

    # Obtener los permisos del usuario
    user_permissions = user.user_permissions.all()

    context = {
        'selected_user': user,
        'user_permissions': user_permissions
    }

    return render(request, 'roles/usuario_permisos.html', context)

@delete_rol_permission
def delete_rolUser(request, user_id, permission_id):

    user = User.objects.get(pk=user_id)
    permission = Permission.objects.get(pk=permission_id)

    if request.method == 'POST':
        user.user_permissions.remove(permission)
        return redirect('administrador:roles')
        
    return render(request, 'roles/delete_usuarioPermiso.html', {'user': user, 'permission': permission})

@add_rol_permission
def add_rolUser(request, user_id):
    
    user = get_object_or_404(User, pk=user_id)
    
    all_permissions = Permission.objects.all()
    missing_permissions = all_permissions.exclude(id__in=user.user_permissions.values_list('id', flat=True))

    context = {
        'user': user,
        'missing_permissions': missing_permissions,
    }

    return render(request, 'roles/add_usuarioPermiso.html', context)

def agregarRol(request, user_id, permission_id):

    user = get_object_or_404(User, pk=user_id)
    permission = get_object_or_404(Permission, pk=permission_id)

    # Agrega la relación de permiso al usuario
    user.user_permissions.add(permission)

    context = {
        'selected_user': user,
        'selected_permission':permission,
    }

    return redirect('administrador:roles')



#Trabajando con blogs
@view_post_permission
def blog(request):
    posts = Post.objects.all()
    return render(request, 'blogs/blog.html', {'posts': posts})

@edit_post_permission
def edit_blog(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        # Si se envió un formulario, procesa los datos
        form = BlogEditForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('administrador:blogs')  # Redirige a la vista de posts después de la edición
    else:
        # Si es una solicitud GET, muestra el formulario de edición
        form = BlogEditForm(instance=post)

    return render(request, 'blogs/editar_post.html', {'form': form, 'post': post})

@delete_post_permission
def delete_blog(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    if request.method == 'POST':
        post.delete()
        return redirect('administrador:blogs')  # Redirige a la vista de lista de usuarios o a donde quieras
    
    return render(request, 'blogs/eliminar_post.html', {'post': post})

@add_post_permission
def add_blog(request):
    if request.method == 'POST':
        form = BlogAddForm(request.POST, request.FILES)
        if form.is_valid():
            # Agrega estas líneas para verificar la imagen que se está recibiendo
            print(request.FILES)  # Deberías ver la información de la imagen en la consola
            post = form.save(commit=False)
            post.fecha_publicacion = datetime.now()
            post.save()
            return redirect('administrador:blogs')
        else:
            print(form.errors)  # Esto te mostrará los errores de validación si los hay
    else:
        form = BlogAddForm()

    template = 'blogs/agregar_post.html'
    return render(request, template, {'form': form})



#Trabajando con Categorias blogs
@view_categoria_permission
def blogsCategorias(request):
    categorias = Categoria.objects.all()
    return render(request, "blogsCategorias/categorias.html", {"categorias": categorias})

@add_categoria_permission
def add_blogCategoria(request):
    if request.method == 'POST':
        form = BlogCategoriaAddForm(request.POST)
        if form.is_valid():
            categoria = form.save(commit=False)
            categoria.fecha_publicacion = datetime.now()  # Asigna la fecha y hora actual en la zona horaria local
            categoria.save()
            return redirect('administrador:blogsCategorias')
    else:
        form = BlogCategoriaAddForm()

    template = 'blogsCategorias/agregar_categoria.html'
    return render(request, template, {'form': form})

""" def delete_blogCategoria(request, postCategoria_id):
    categoria = get_object_or_404(Post, id=postCategoria_id)
    
    if request.method == 'POST':
        categoria.delete()
        return redirect('administrador:blogsCategorias')  # Redirige a la vista de lista de usuarios o a donde quieras
    
    return render(request, 'blogsCategorias/eliminar_categoria.html', {'categoria': categoria}) """

@edit_categoria_permission
def edit_blogCategoria(request, postCategoria_id):
    categoria = get_object_or_404(Categoria, id=postCategoria_id)

    if request.method == 'POST':
        # Si se envió un formulario, procesa los datos
        form = BlogCategoriaEditForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
            return redirect('administrador:blogsCategorias')  # Redirige a la vista de posts después de la edición
    else:
        # Si es una solicitud GET, muestra el formulario de edición
        form = BlogCategoriaEditForm(instance=categoria)

    return render(request, 'blogsCategorias/editar_categoria.html', {'form': form, 'categoria': categoria})



#Trabajando con servicios
@view_servicio_permission
def servicios(request):
    servicios = Servicio.objects.all()
    return render(request, "servicio/servicios.html", {"servicios": servicios})

@add_servicio_permission
def add_servicios(request):
    if request.method == 'POST':
        form = ServicioAddForm(request.POST, request.FILES)
        if form.is_valid():
            # Agrega estas líneas para verificar la imagen que se está recibiendo
            print(request.FILES)  # Deberías ver la información de la imagen en la consola
            servicio = form.save(commit=False)
            servicio.fecha_publicacion = datetime.now()
            servicio.save()
            return redirect('administrador:servicios')
        else:
            print(form.errors)  # Esto te mostrará los errores de validación si los hay
    else:
        form = ServicioAddForm()

    template = 'servicio/agregar_servicio.html'
    return render(request, template, {'form': form})

@edit_servicio_permission
def edit_servicios(request, servicio_id):
    servicio = get_object_or_404(Servicio, id=servicio_id)

    if request.method == 'POST':
        # Si se envió un formulario, procesa los datos
        form = ServicioEditForm(request.POST, instance=servicio)
        if form.is_valid():
            form.save()
            return redirect('administrador:servicios')  # Redirige a la vista de posts después de la edición
    else:
        # Si es una solicitud GET, muestra el formulario de edición
        form = ServicioEditForm(instance=servicio)

    return render(request, 'servicio/editar_servicio.html', {'form': form, 'servicio': servicio})

@delete_servicio_permission
def delete_servicios(request, servicio_id):
   
    servicio = get_object_or_404(Servicio, id=servicio_id)
    
    if request.method == 'POST':
        servicio.delete()
        return redirect('administrador:servicios')  # Redirige a la vista de lista de usuarios o a donde quieras
    

administrador/templates/usuarios/agregar_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>Agregar Usuario</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: rgba(24, 64, 8);
            margin: 0;
            padding: 0;
        }
        h1 {
            color: #fdfdfd;
            text-align: center;
            margin-top: 30px;
            background-color: rgba(24, 64, 8);
        }
        form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }
        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }
        a {
            display: block;
            text-align: center;
            margin-top: 15px;
            color: #333;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <h1>Agregar Usuario</h1>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-info">Agregar Usuario</button>
        <a href="{% url 'administrador:usuarios' %}" class="btn btn-danger">Cancelar</a>
    </form>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</html>

administrador/templates/usuarios/editar_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>Editar Usuario</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: rgba(24, 64, 8);
            margin: 0;
            padding: 0;
            
            min-height: 100vh;
        }
        h1 {
            color: #ffffff;
            text-align: center;
            margin-bottom: 20px;
            background-color: rgba(24, 64, 8);
        }
        form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }
        
       
    </style>
</head>
<body>
    <h1>Editar Usuario</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-info">Guardar Cambios</button>
        <a href="{% url 'administrador:usuarios' %}" class="btn btn-danger">Cancelar</a>
    </form>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</html>

administrador/templates/usuarios/eliminar_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>Eliminar Usuario</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: rgba(24, 64, 8);
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
        .container {
            max-width: 400px;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px;
        }
        p {
            color: #555;
            text-align: center;
            margin-bottom: 30px;
        }
        
       
    </style>
</head>
<body>
    
    <div class="container">
        <h1>Eliminar Usuario</h1>
        <p>¿Estás seguro de que deseas eliminar al usuario <strong>{{ user.username }}</strong>?</p>
        
        <form method="post">
            {% csrf_token %}
            <td style="text-align: center;">
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a href="{% url 'administrador:usuarios' %}" class="btn btn-secondary">Cancelar</a>
            </td>
            
        </form>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</html>

administrador/templates/usuarios/usuarios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>Lista de Usuarios</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: rgba(24, 64, 8);
        }

        h1 {
            text-align: center;
            padding: 20px 0;
            background-color: rgba(24, 64, 8);
            color: white;
            margin: 0;
        }

        a {
            text-decoration: none;
            color: #007bff;
        }

        a:hover {
            text-decoration: underline;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            border: 1px solid #dee2e6;
            background-color: white;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        th, td {
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .btn-group {
            display: flex;
            gap: 10px;
        }

        .btn {
            padding: 8px 16px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        
    </style>
</head>
<body>
    <h1>Lista de Usuarios</h1>
    <div class="container">
        <td >
            <a href="{% url 'administrador:usuariosAdd' %}" class="btn btn-info">Agregar Usuario</a>
            <a href="{% url 'Home' %}" class="btn btn-dark">Cancelar</a><br><br>
        </td>
        <table>
            <tr>
                <th>Nombre de Usuario</th>
                <th>Email</th>
                <th>Acción</th>
            </tr>
            {% for user in users %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td class="btn-group">
                    <a href="{% url 'administrador:usuariosEdit' user.id %}" class="btn btn-warning">Editar</a>
                    <a href="{% url 'administrador:usuariosDelet' user.id %}" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</html>